[project]
name = "fortmes.pypi"
version = "0.1.21"
license = { file = "LICENSE" }
description = "Python package for fortmes login"
readme = "README.md"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[dependencies]
# Add your project dependencies here
httpx = ">=0.18.2"
logging = ">=0.4.9.6"



[project.urls]
documentation = "https://github.com/fortmes/fortmes-pypi"
homepage = "https://github.com/fortmes/fortmes-pypi"
repository = "https://github.com/fortmes/fortmes-pypi"
