[tool.poetry]
name = "py-book-util"
version = "0.1.65"
description = ""
authors = ["\"Richard.Tang\" <tang_can@qq.com>"]
readme = "README.md"
packages = [{include = "py_book_util"}]

[tool.poetry.dependencies]
python = "^3.8"
ipython = "^8.5.0"
myst-nb = "^0.17.1"
pillow = "^9.4.0"
selenium = "^4.7.2"
invoke = "^2.2.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"



[tool.poetry.group.test.dependencies]
behave = "^1.2.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
