[tool.poetry]
name = "mjurav-de2-1"
version = "0.1.4"
description = ""
authors = ["Martynas <martynas.j@oxylabs.io>"]
readme = "README.md"
packages = [{include = "data_transformation", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pydantic = "^2.4.2"
numpy = "^1.26.1"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
flake8-annotations-complexity = "^0.0.6"
flake8-bandit = "^4.1.1"
flake8-breakpoint = "^1.1.0"
flake8-bugbear = "^22.12.6"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.5.0"
flake8-eradicate = "^1.4.0"
flake8-expression-complexity = "^0.0.9"
flake8-if-expr = "^1.0.4"
flake8-isort = "^4.0.0"
flake8-print = "^4.0.0"
flake8-pytest = "^1.3"
flake8-pytest-style = "^1.5.0"
flake8-requirements = "^1.5.0"
flake8-return = "^1.1.3"
flake8-commas = "^2.0.0"
flake8-alfred = "^1.1.1"
flake8-blind-except = "^0.2.0"
flake8-debugger = "^4.0.0"
flake8-mutable = "^1.2.0"
flake8-pep3101 = "^1.3.0"
flake8-tidy-imports = "^4.3.0"
flake8 = "^5.0.0"
mypy = "^1.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"