name: iDDS-doma
dependencies:
- python==3.6
- pip
- pip:
  - futures                          # multiple process/threads
  - panda-client-light     # panda client
  - idds-common==1.3.30
  - idds-workflow==1.3.30