[tool.poetry]
name = "repairshopr-api"
version = "0.1.63"
description = ""
authors = ["Chris Busillo <info@shinycomputers.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
toml = "^0.10.2"
requests = "^2.31.0"
pytz = "^2023.3.post1"
black = "^23.10.1"
tenacity = "^8.2.3"
django = "^4.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
