[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "housing_library_5512"
version = "0.1"
description = "Sample code for coding practice"
readme = "README.md"
authors = [{ 'name' = "Chandra Sekhar", 'email' = "chandra.lella@tigeranalytics.com" }]
license = { file = "LICENSE" }
 
classifiers = [
    "Programming Language :: Python :: 3",
]
keywords = ["housing","data training"]
 
dependencies = [ "numpy", "pandas", "scikit-learn"]
 
requires-python = ">=3.11"

[project.urls]
Homepage = "https://github.com/chandra8278/mle-training"
 
[project.scripts]
ingest_data = "ingest_data"
train_data = "train"
score = "score"