[tool.poetry]
name = "fga_demo"
version = "0.1.3"
description = "An event driven governance solution, that provides data cataloguing, profiling and data quality processing after ingestion."
authors = ["Ghana BigSpark"]
readme = "README.md"
license = "MIT"
packages = [{include = "fga_demo", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0"
selenium = "^4"
webdriver-manager = "^4"
gql = "^3"
boto3 = "^1"
rich = "^13"

[tool.poetry.scripts]
fga = "fga_demo.cli.cli:app"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
