[project]
name = "doxg"
version = "0.4.1"
description = "useful contents of mine"
authors = [
    { name = "doxg", email = "praze74@gmail.com" },
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"

[project.license]
text = "MIT"

[project.scripts]
doxg-imp = "doxg:imp"
doxg-pic = "doxg:pic"
doxg-who = "doxg:who"
doxg-game = "doxg.game:coin_game"

[project.urls]
Homepage = "https://github.com/doxgxxn/doxg"
"Bug Tracker" = "https://github.com/doxgxxn/doxg/issues"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.2",
    "pytest-cov>=4.1.0",
]
