[project]
name = "cheesebuild"
version = "1.2.2"
authors = [
  { name="afoxotter", email="otter@afox.page" },
]
description = "A python build system for GCC, but with CHEESE."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/chrismdjr/cheesebuild"
"Bug Tracker" = "https://github.com/chrismdjr/cheesebuild/issues"
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"