[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "audio_normalizer"
version = "1.1"
authors = [
  { name="Matthias Christopher Schmid", email="schmid.mat93@gmail.com" },
]
description = "Audio Normalizer for MP3 and WAV files"
readme = "README.md"
requires-python = ">=3.7"
dynamic = ["dependencies"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: Microsoft :: Windows",
]

[project.urls]
"Homepage" = "https://github.com/MatthiasSchmid93/AudioNormalizer"
"Bug Tracker" = "https://github.com/MatthiasSchmid93/AudioNormalizer/issues"