[tool.poetry]
name = "unctl"
packages = [
  {include = "unctl"}
]
version = "0.1.0"
description = "A health check and RCA tool for kubernetes"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
colorama = "^0.4.6"
openai = "^0.28.1"
tiktoken = "^0.5.1"
prettytable = "^3.9.0"
kubernetes = "^28.1.0"
pydantic = "^2.4.2"
croniter = "^2.0.1"
backoff = "^2.2.1"

[tool.poetry.scripts]
unctl = "unctl.__main__:unctl"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
