[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[project]
name = "unstract-connectors"
version = "0.0.2"
description = "All connectors that are part of the Unstract platform"
authors = [
    { name = "Zipstack Inc.", email = "devsupport@zipstack.com" },
]
dependencies = [
    "google-auth==2.20.0",
    "google-cloud-secret-manager==2.16.1",
    "google-cloud-storage==2.9.0",
    "s3fs[boto3]==2023.6.0",
    "PyDrive2[fsspec]==1.15.4",
    "oauth2client==4.1.3",
    "dropboxdrivefs==1.3.1",
    "boxfs==0.2.1",
    "psycopg2-binary==2.9.9",
    "snowflake-connector-python[pandas]==3.0.4",
    "google-cloud-bigquery==3.11.4",
    "pymssql==2.2.8",
    "PyMySQL==1.1.0",
]
requires-python = ">=3.9"
readme = "README.md"
classifiers = [
    "Programming Language :: Python",
]

[project.license]
text = "MIT"

[tool.pdm.build]
includes = [
    "src",
]
package-dir = "src"

[tool.pdm.dev-dependencies]
dev = [
    "pre-commit~=3.3.1",
    "pytest>=7.4.2",
    "ipython~=8.13.2",
    "ipdb~=0.13.13",
    "flake8~=6.0.0",
    "mypy~=1.2.0",
    "flake8-pyproject~=1.2.2",
    "black~=23.3.0",
    "isort~=5.12.0",
    "absolufy-imports~=0.3.1",
    "docutils~=0.20.1",
    "autopep8~=2.0.2",
    "types-requests~=2.31.0.6",
    "types-redis~=4.6.0.3",
    "types-PyYAML~=6.0.12.12",
    "types-PyMySQL~=1.1.0.1",
    "types-pyOpenSSL~=23.2.0.2",
]

[tool.black]
line-length = 88
target-version = [
    "py39",
]

[tool.pycln]
all = true

[tool.pyupgrade]
keep_dict_typing = true

[tool.flake8]
max-line-length = 88
exclude = "pyproject.toml"

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
profile = "black"

[tool.mypy]
python_version = 3.9
show_error_codes = true
pretty = true
exclude = [
    "tests/",
]
ignore_missing_imports = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_ignores = true
warn_return_any = true
warn_unused_configs = true
show_column_numbers = true
check_untyped_defs = true
follow_imports = "silent"
strict = true
implicit_reexport = true
