[tool.poetry]
name = "netbox-subsystems"
version = "0.1.3"
description = ""
authors = ["izakharov <ilya.zakharov@domrf.ru>"]
readme = "README.md"
packages = [{include = "netbox_subsystems"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
