[tool.poetry]
name = "ytpa-utils"
version = "0.1.5"
description = "Utils for the YouTube Predictive Analytics system"
authors = ["Johannes Traa"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.5"
pandas = "^2.0.3"
numpy = "^1.25.2"
pytest = "^7.4.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"