[project]
name = "spectro-utils"
version = "0.1.4"
description = "Add a short description here"
authors = [
    { name = "brian23-code", email = "brian23@mirai.re" }
]
dependencies = [
    "numpy>=1.24.4",
    "librosa>=0.10.1",
    "Pillow>=10.1.0",
    "pysoundfile>=0.9.0.post1",
    "tqdm>=4.66.1",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true

[tool.hatch.metadata]
allow-direct-references = true
