[tool.poetry]
name = "jira2branch"
version = "0.5.0"
description = "Takes a JIRA issue and creates a git branch"
authors = ["Tiago Pereira <tiago@tiagoafpereira.net>"]
readme = "README.md"
license = "MIT"
classifiers = [
	"License :: OSI Approved :: MIT License",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.8",
]

[tool.poetry.dependencies]
python = "^3.10"
click = "8.1.3"
jira = "3.5.0"
halo = "0.0.31"
Unidecode = "1.3.6"
GitPython = "3.1.31"
python-gitlab = "3.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
jira2branch = "jira2branch.__main__:cli"
