[tool.poetry]
name = "thymus-ast"
version = "0.1.4"
description = "A set of tools to build ASTs for different NOS"
authors = ["Igor Malyushkin <gmalyushkin@gmail.com>"]
readme = "README.md"
packages = [{include = "thymus_ast"}]

[tool.poetry.dependencies]
python = "^3.8.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
